// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HelpDesk.Models
{
    public partial class KnowledgeBase
    {
        public int KnowledgeBaseId { get; set; }
        public string Title { get; set; }
        public string Solution { get; set; }
        public DateTime Date { get; set; }
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }
    }
}