// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HelpDesk.Models
{
    public partial class Message
    {
        public int MessageId { get; set; }
        public string MessageContent { get; set; }
        public DateTime DateTime { get; set; }
        public string Sender { get; set; }
        public int TicketId { get; set; }

        public virtual Ticket Ticket { get; set; }
    }
}