// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HelpDesk.Models
{
    public partial class Status
    {
        public Status()
        {
            Ticket = new HashSet<Ticket>();
        }

        public int StatusId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}